// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: kms/v1/kms.proto

package kmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KMS_GetCredential_FullMethodName = "/kms.v1.KMS/GetCredential"
)

// KMSClient is the client API for KMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KMS hands out short-lived storage credentials.
type KMSClient interface {
	// GetCredential returns a credential for the buckets the caller is
	// entitled to, as derived from its authentication token (JWT).
	GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error)
}

type kMSClient struct {
	cc grpc.ClientConnInterface
}

func NewKMSClient(cc grpc.ClientConnInterface) KMSClient {
	return &kMSClient{cc}
}

func (c *kMSClient) GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialResponse)
	err := c.cc.Invoke(ctx, KMS_GetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KMSServer is the server API for KMS service.
// All implementations must embed UnimplementedKMSServer
// for forward compatibility.
//
// KMS hands out short-lived storage credentials.
type KMSServer interface {
	// GetCredential returns a credential for the buckets the caller is
	// entitled to, as derived from its authentication token (JWT).
	GetCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error)
	mustEmbedUnimplementedKMSServer()
}

// UnimplementedKMSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKMSServer struct{}

func (UnimplementedKMSServer) GetCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedKMSServer) mustEmbedUnimplementedKMSServer() {}
func (UnimplementedKMSServer) testEmbeddedByValue()             {}

// UnsafeKMSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KMSServer will
// result in compilation errors.
type UnsafeKMSServer interface {
	mustEmbedUnimplementedKMSServer()
}

func RegisterKMSServer(s grpc.ServiceRegistrar, srv KMSServer) {
	// If the following call panics, it indicates UnimplementedKMSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KMS_ServiceDesc, srv)
}

func _KMS_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMS_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServer).GetCredential(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KMS_ServiceDesc is the grpc.ServiceDesc for KMS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KMS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kms.v1.KMS",
	HandlerType: (*KMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredential",
			Handler:    _KMS_GetCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kms/v1/kms.proto",
}
