name: kms
version: 0.2.0
language: go

targets:
  test-unittest:
    steps:
      - runner: go
        config:
          buildTags: ["unittest"]
      - runner: coverage-upload
    inputs: ["self"]

  build:
    steps:
      - runner: go
      - runner: git-diff
        config:
          paths:
            - internal

    inputs: ["self"]

  lint:
    steps:
      - runner: go
        config:
          checkBuildConstraints:
            enable: false
            rules:
              - includePatterns:
                  ["**/internal/**/*_test.go", "**/pkg/**/*_test.go"]
                constraints: ["test && unittest"]
              - includePatterns: ["**/test/**/*_test.go"]
                constraints: ["test && integration"]

    inputs: ["self"]

  image:
    steps:
      - runner: nix
    inputs: ["self"]

  test-nix:
    inputs: &ins-nix ["self"]
    stage: "aux"
    steps:
      - runnerID: quitsh::test-go
  build-nix:
    stage: "aux"
    steps:
      - runnerID: quitsh::build-go
    inputs: *ins-nix
