name: kms
version: 0.2.0
language: go

targets:
  test-unittest:
    steps:
      - runner: go
        config:
          buildTags: ["unittest"]
      - runner: coverage-upload

  test-integration:
    steps:
      - runner: go
        config:
          submodules:
            - test
          args:
            - "--timeout=20m"
          buildTags: ["integration"]
      - runner: coverage-upload

  build:
    steps:
      - runner: go
      - runner: git-diff
        config:
          paths:
            - internal

  lint:
    steps:
      - runner: go
        config:
          checkBuildConstraints:
            enable: false
            rules:
              - includePatterns:
                  ["**/internal/**/*_test.go", "**/pkg/**/*_test.go"]
                constraints: ["test && unittest"]
              - includePatterns: ["**/test/**/*_test.go"]
                constraints: ["test && integration"]

  image:
    steps:
      - runner: nix

  test-nix:
    inputs: &ins-nix ["self"]
    stage: "aux"
    steps:
      - runnerID: quitsh::test-go
  build-nix:
    stage: "aux"
    steps:
      - runnerID: quitsh::build-go
    inputs: *ins-nix
