# Quitsh settings: See all of them `quitsh config write --output test.yaml`.
commands:
  root:
    logLevel: info
    globalOutput: true
    # If not set, its the root dir (so its safe in local dev.)
    outputDir: "$CI_MODOS_SCRATCH_DIR"

  execArgs:
    tags:
      - ci

nix:
  cache:
    ssh:
      enable: true

      hostName: nix-cache.swisscustodian.ch
      hostPublicKey: |-
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMP4u5o2KC6f2OpO4b1GRQzhdcBheLENmS++xw1y5JvY
      write:
        privateKeyEnv: NIX_CACHE_SSH_WRITE_KEY
