# Quitsh settings: See all of them `quitsh config write --output test.yaml`.
commands:
  root:
    logLevel: info
    globalOutput: true
    # If not set, its the root dir (so its safe in local dev.)
    outputDir: "$CI_MODOS_SCRATCH_DIR"

  execArgs:
    tags:
      - ci
