[[repos]]
repo = "builtin"

  [[repos.hooks]]
  id = "check-added-large-files"

  [[repos.hooks]]
  id = "check-merge-conflict"

  [[repos.hooks]]
  id = "end-of-file-fixer"

  [[repos.hooks]]
  id = "mixed-line-ending"

  [[repos.hooks]]
  id = "trailing-whitespace"

[[repos]]
repo = "local"

  [[repos.hooks]]
  id = "treefmt"
  name = "treefmt"
  language = "system"
  entry = "just format"
  pass_filenames = false
  require_serial = true

  [[repos.hooks]]
  id = "quitsh"
  name = "quitsh"
  language = "system"
  entry = "./tools/quitsh/tools/scripts/update-quitsh-version.sh"
  pass_filenames = false
  require_serial = true
