// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/kms.proto

package kmsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialRequest) Reset() {
	*x = GetCredentialRequest{}
	mi := &file_v1_kms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialRequest) ProtoMessage() {}

func (x *GetCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetCredentialRequest) Descriptor() ([]byte, []int) {
	return file_v1_kms_proto_rawDescGZIP(), []int{0}
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_v1_kms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_v1_kms_proto_rawDescGZIP(), []int{1}
}

var File_v1_kms_proto protoreflect.FileDescriptor

const file_v1_kms_proto_rawDesc = "" +
	"\n" +
	"\fv1/kms.proto\x12\x06kms.v1\"\x16\n" +
	"\x14GetCredentialRequest\"\x17\n" +
	"\x15GetCredentialResponse2Z\n" +
	"\n" +
	"KMSService\x12L\n" +
	"\rGetCredential\x12\x1c.kms.v1.GetCredentialRequest\x1a\x1d.kms.v1.GetCredentialResponseB@Z>github.com/sdsc-ordes/modos-rs/components/kms/pkg/api/v1;kmsv1b\x06proto3"

var (
	file_v1_kms_proto_rawDescOnce sync.Once
	file_v1_kms_proto_rawDescData []byte
)

func file_v1_kms_proto_rawDescGZIP() []byte {
	file_v1_kms_proto_rawDescOnce.Do(func() {
		file_v1_kms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_kms_proto_rawDesc), len(file_v1_kms_proto_rawDesc)))
	})
	return file_v1_kms_proto_rawDescData
}

var file_v1_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_kms_proto_goTypes = []any{
	(*GetCredentialRequest)(nil),  // 0: kms.v1.GetCredentialRequest
	(*GetCredentialResponse)(nil), // 1: kms.v1.GetCredentialResponse
}
var file_v1_kms_proto_depIdxs = []int32{
	0, // 0: kms.v1.KMSService.GetCredential:input_type -> kms.v1.GetCredentialRequest
	1, // 1: kms.v1.KMSService.GetCredential:output_type -> kms.v1.GetCredentialResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_kms_proto_init() }
func file_v1_kms_proto_init() {
	if File_v1_kms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_kms_proto_rawDesc), len(file_v1_kms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_kms_proto_goTypes,
		DependencyIndexes: file_v1_kms_proto_depIdxs,
		MessageInfos:      file_v1_kms_proto_msgTypes,
	}.Build()
	File_v1_kms_proto = out.File
	file_v1_kms_proto_goTypes = nil
	file_v1_kms_proto_depIdxs = nil
}
