name: normal
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: nix-hash
        run: just ci::run quitsh nix fix-hash

  checks:
    runs-on: ubuntu-latest
    needs:
      - nix-hash
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false

      matrix:
        include:
          - name: lint-security
            command: just ci::run quitsh exec-target "global::lint-security"
            allow_failure: true

          - name: lint-kms
            command: just ci::run quitsh lint -c "kms"
          - name: lint-comp-rust
            command: just ci::run quitsh lint -c "comp-rust"

          - name: build-kms
            command: just ci::run quitsh build -c "kms"

          - name: build-comp-rust
            command: just ci::run quitsh build -c "comp-rust"

          - name: test-kms
            command: just ci::run quitsh test -c "kms"
          - name: test-comp-rust
            command: just ci::run quitsh test -c "comp-rust"
          - name: test-quitsh
            command: just ci::run quitsh test -c "quitsh"

          - name: image-kms
            command: just ci::run quitsh image -c "kms"
          - name: image-comp-rust
            command: just ci::run quitsh image -c "comp-rust"

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_cache_name: "${{ secrets.CACHIX_CACHE_NAME }}"
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: ${{ matrix.name }}
        continue-on-error: ${{ matrix.allow_failure }}
        run: ${{ matrix.command }}

      - name: ${{ matrix.name }}-artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.name }}
          path: |
            .output/run/process-compose
          if-no-files-found: ignore
          retention-days: 3

  # Aggregate check for protection rule.
  checks-all:
    if: always()
    needs:
      - checks # your matrix job
    runs-on: ubuntu-latest
    steps:
      - name: Verify all matrix jobs passed
        run: |
          if [[ "${{ needs.checks.result }}" != "success" ]]; then
            echo "One or more checks failed: ${{ needs.checks.result }}"
            exit 1
          fi
